CREATE TABLE [dbo].[staff] (
    [staff_id]             INT           NOT NULL,
    [foxpro_id]            CHAR (50)     NULL,
    [logon_staff_id]       INT           NULL,
    [transaction_staff_id] INT           NULL,
    [create_date]          DATETIME      NULL,
    [modify_date]          DATETIME      NULL,
    [staff_categories_id]  INT           NULL,
    [name_last]            CHAR (20)     NULL,
    [name_middle]          CHAR (20)     NULL,
    [name_first]           CHAR (20)     NULL,
    [nickname]             CHAR (20)     NULL,
    [social_security]      CHAR (11)     NULL,
    [password]             CHAR (10)     NULL,
    [security_level]       DECIMAL (18)  NULL,
    [gender]               CHAR (1)      NULL,
    [birthdate]            DATETIME      NULL,
    [hiredate]             DATETIME      NULL,
    [termination_date]     DATETIME      NULL,
    [phone_res]            CHAR (15)     NULL,
    [phone_bus]            CHAR (15)     NULL,
    [phone_fax]            CHAR (15)     NULL,
    [phone_page]           CHAR (15)     NULL,
    [phone_cell]           CHAR (15)     NULL,
    [phone_other]          CHAR (15)     NULL,
    [email1]               CHAR (30)     NULL,
    [email2]               CHAR (30)     NULL,
    [notes]                VARCHAR (500) NULL,
    [cal_color]            CHAR (16)     NULL,
    [fgcolor]              CHAR (16)     NULL,
    [seniority_level]      INT           NULL,
    [notused]              BIT           NULL,
    [comm_service]         FLOAT (53)    NULL,
    [comm_retail]          FLOAT (53)    NULL,
    [comm_gc]              FLOAT (53)    NULL,
    [comm_package]         FLOAT (53)    NULL,
    [auto_email]           BIT           NULL,
    [SSN]                  CHAR (11)     NULL,
    [pay_rate]             REAL          NULL,
    [license_number]       CHAR (20)     NULL,
    [license_exp]          DATETIME      NULL,
    [evaluation_date]      DATETIME      NULL,
    [picture_url]          CHAR (30)     NULL,
    [comm_categories_id]   INT           NULL
);

