CREATE TABLE [dbo].[staff] (
    [ID]                 INT           IDENTITY (1000, 1) NOT NULL,
    [dtCreateDate]       DATETIME2 (7) NULL,
    [nStaffCategoriesID] INT           NULL,
    [cNameLast]          NVARCHAR (50) NULL,
    [cNameMiddle]        NVARCHAR (50) NULL,
    [cNameFirst]         NVARCHAR (50) NULL,
    [cNickname]          NVARCHAR (50) NULL,
    [cSIN]               NVARCHAR (50) NULL,
    [cPassword]          CHAR (10)     NULL,
    [nSecurity_level]    INT           NULL,
    [nGenderID]          INT           NULL,
    [dtBirthDate]        DATETIME2 (7) NULL,
    [dtHireDate]         DATETIME2 (7) NULL,
    [dtTerminationDate]  DATETIME      NULL,
    [cPhoneRes]          NVARCHAR (50) NULL,
    [cPhoneBus]          NVARCHAR (50) NULL,
    [cPhoneFax]          NVARCHAR (50) NULL,
    [cPhonePage]         NVARCHAR (50) NULL,
    [cPhoneCell]         NVARCHAR (50) NULL,
    [cPhoneOther]        NVARCHAR (50) NULL,
    [cEmail1]            NVARCHAR (50) NULL,
    [cEmail2]            NVARCHAR (50) NULL,
    [cNotes]             VARCHAR (MAX) NULL,
    [nSeniorityLevel]    INT           NULL,
    [nCommCategoriesID]  INT           NULL,
    [nLicenseNumber]     CHAR (20)     NULL,
    [dtLicenseExpiry]    DATETIME2 (7) NULL,
    [dtEvaluationDate]   DATETIME2 (7) NULL,
    [bNotActive]         BIT           NULL,
    [bDeleted]           BIT           NULL,
    [dtDateDeleted]      DATETIME2 (7) NULL,
    CONSTRAINT [PK_staff] PRIMARY KEY CLUSTERED ([ID] ASC)
);



