CREATE TABLE [dbo].[vendors] (
    [vendors_id]           INT            IDENTITY (1000, 1) NOT NULL,
    [dtCreateDate]         DATETIME2 (7)  CONSTRAINT [DF_vendors_dtCreateDate] DEFAULT (getdate()) NULL,
    [account_no]           CHAR (20)      NULL,
    [notes]                NVARCHAR (MAX) NULL,
    [foxpro_id]            CHAR (50)      NULL,
    [create_date]          DATETIME       CONSTRAINT [DF_vendors_create_date] DEFAULT (getdate()) NULL,
    [modify_date]          DATETIME       NULL,
    [logon_staff_id]       INT            NULL,
    [transaction_staff_id] INT            NULL,
    [name]                 NVARCHAR (255) NULL,
    [address1]             NVARCHAR (255) NULL,
    [address2]             NVARCHAR (255) NULL,
    [city]                 NVARCHAR (255) NULL,
    [state]                NVARCHAR (255) NULL,
    [postal_code]          CHAR (10)      NULL,
    [state_other]          CHAR (15)      NULL,
    [zip]                  NVARCHAR (255) NULL,
    [country]              NVARCHAR (255) NULL,
    [areacode]             CHAR (3)       NULL,
    [phone]                NVARCHAR (255) NULL,
    [email]                NVARCHAR (255) NULL,
    [website]              NVARCHAR (255) NULL,
    [rep]                  NVARCHAR (255) NULL,
    [fax_areacode]         CHAR (3)       NULL,
    [fax_phone]            NVARCHAR (255) NULL,
    [cell_areacode]        CHAR (3)       NULL,
    [cell_phone]           NVARCHAR (255) NULL,
    [password]             CHAR (10)      NULL,
    [sw2001_id]            INT            NULL,
    [Old_XREF_ID]          VARCHAR (20)   NULL,
    [cDescription]         NVARCHAR (255) NULL,
    [nGalProID]            INT            NULL,
    [cTitle]               NVARCHAR (255) NULL,
    [cNameFirst]           NVARCHAR (255) NULL,
    [cNameLast]            NVARCHAR (255) NULL,
    [cPosition]            NVARCHAR (255) NULL,
    [cPhoneRes]            NVARCHAR (255) NULL,
    [cPhoneOther]          NVARCHAR (255) NULL,
    [cPhoneOther1]         NVARCHAR (255) NULL,
    [cSalesRep2]           NVARCHAR (255) NULL,
    [cAssistant]           NVARCHAR (255) NULL,
    [cAssistantPhone]      NVARCHAR (255) NULL,
    [dtOriginalCreateDate] DATETIME       NULL,
    [nVendorMasterID]      INT            NULL,
    [cSalesRep]            NVARCHAR (50)  NULL,
    [cmpDisplay]           AS             (ltrim((((isnull([cNameFirst],'')+' ')+isnull([cNameLast],''))+case when [cNameLast] IS NOT NULL AND [cNameLast]<>'' AND [name] IS NOT NULL AND [name]<>'' then ', ' else '' end)+isnull([name],''))),
    [bDeleted]             BIT            NULL,
    [dtDeleteDate]         DATETIME2 (7)  NULL,
    CONSTRAINT [PK_vendors] PRIMARY KEY CLUSTERED ([vendors_id] ASC) WITH (FILLFACTOR = 90)
);

