CREATE TABLE [dbo].[worksSet] (
    [worksSet_id]     INT             NOT NULL,
    [stax]            FLOAT (53)      NOT NULL,
    [spaname]         CHAR (40)       NOT NULL,
    [logo]            IMAGE           NULL,
    [retover]         BIT             NOT NULL,
    [usecharge]       BIT             NOT NULL,
    [dbfpath]         CHAR (35)       NOT NULL,
    [defstate]        CHAR (2)        NOT NULL,
    [clinum]          CHAR (10)       NOT NULL,
    [cashreg]         BIT             NOT NULL,
    [usetips]         BIT             NOT NULL,
    [usemark]         BIT             NOT NULL,
    [usemem]          BIT             NOT NULL,
    [useretcom]       BIT             NOT NULL,
    [grtax]           FLOAT (53)      NOT NULL,
    [tickgroup]       BIT             NOT NULL,
    [normpath]        CHAR (40)       NOT NULL,
    [delempty]        BIT             NOT NULL,
    [retdfltp]        BIT             NOT NULL,
    [payregonly]      BIT             NOT NULL,
    [noregpass]       BIT             NOT NULL,
    [nextauto]        BIT             NOT NULL,
    [autochange]      BIT             NOT NULL,
    [autoopen]        BIT             NOT NULL,
    [promptreg]       BIT             NOT NULL,
    [promptfin]       BIT             NOT NULL,
    [thertc]          BIT             NOT NULL,
    [thervs]          BIT             NOT NULL,
    [thercomm]        BIT             NOT NULL,
    [thermail]        BIT             NOT NULL,
    [therps]          BIT             NOT NULL,
    [thermenu]        BIT             NOT NULL,
    [nockpub]         BIT             NOT NULL,
    [baloff]          FLOAT (53)      NOT NULL,
    [activeoff]       FLOAT (53)      NOT NULL,
    [todisc]          BIT             NOT NULL,
    [alwaysbal]       BIT             NOT NULL,
    [usehotel]        BIT             NOT NULL,
    [decnog]          BIT             NOT NULL,
    [gctax]           BIT             NOT NULL,
    [mgca]            BIT             NOT NULL,
    [thersrnum]       BIT             NOT NULL,
    [usefood]         BIT             NOT NULL,
    [defarea]         CHAR (3)        NOT NULL,
    [defcity]         CHAR (30)       NOT NULL,
    [defzip]          CHAR (10)       NOT NULL,
    [usether]         BIT             NOT NULL,
    [useclock]        BIT             NOT NULL,
    [uselodge]        BIT             NOT NULL,
    [usedest]         BIT             NOT NULL,
    [maxqty]          FLOAT (53)      NOT NULL,
    [useqb]           BIT             NOT NULL,
    [qbar]            CHAR (30)       NOT NULL,
    [qbst]            CHAR (30)       NOT NULL,
    [qbstn]           CHAR (30)       NOT NULL,
    [qbsti]           CHAR (30)       NOT NULL,
    [qbloc]           CHAR (30)       NOT NULL,
    [notax1]          BIT             NOT NULL,
    [notax2]          BIT             NOT NULL,
    [therblock]       BIT             NOT NULL,
    [catmax]          BIT             NOT NULL,
    [maxreg]          FLOAT (53)      NOT NULL,
    [maxregday]       FLOAT (53)      NOT NULL,
    [therscale]       BIT             NOT NULL,
    [popkind]         FLOAT (53)      NOT NULL,
    [mssg]            BIT             NOT NULL,
    [mocr]            BIT             NOT NULL,
    [printdiff]       BIT             NOT NULL,
    [useicv]          BIT             NOT NULL,
    [greyout]         BIT             NULL,
    [license_code]    CHAR (30)       NULL,
    [smsUsername]     CHAR (10)       NULL,
    [smsPassword]     CHAR (10)       NULL,
    [address1]        CHAR (40)       NULL,
    [address2]        CHAR (40)       NULL,
    [city]            CHAR (30)       NULL,
    [state]           CHAR (2)        NULL,
    [state_other]     CHAR (15)       NULL,
    [zip]             CHAR (10)       NULL,
    [postal_code]     CHAR (10)       NULL,
    [country]         CHAR (20)       NULL,
    [phone]           CHAR (10)       NULL,
    [areacode]        CHAR (3)        NULL,
    [countrycode]     CHAR (3)        NULL,
    [url]             CHAR (40)       NULL,
    [email]           CHAR (30)       NULL,
    [fax]             CHAR (10)       NULL,
    [fax_areacode]    CHAR (3)        NULL,
    [fax_countrycode] CHAR (3)        NULL,
    [real_data]       BIT             NULL,
    [NoFetchAll]      BIT             NULL,
    [spaworks_db]     VARCHAR (30)    NULL,
    [clubworks_db]    VARCHAR (30)    NULL,
    [roomworks_db]    VARCHAR (30)    NULL,
    [punchworks_db]   VARCHAR (30)    NULL,
    [nTaxRate]        NUMERIC (18, 6) NULL,
    [nTaxRate1]       NUMERIC (18, 6) NULL
);

